### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by chrisnharvey** [wxphp/wxphp#96] opened 2015-05-19 11:15 UTC
Since PHP 7 has a projected release date of November. It would be great if we could get wxPHP working on PHP 7 before then so we can be ready the day it is released.

**Comment by jgmdev** [comment] 2015-05-19 16:17
True! At the moment I haven't got time for doing it my self, but I also opened a ticket some time ago #61 with links that explain the internal changes, this one is also pretty helpful https://wiki.php.net/phpng-upgrading. I hope some one else can start working on this, because as things are going I haven't found the time lately...

**Comment by chrisnharvey** [comment] 2015-05-19 17:10
Totally understand. There is only so much you can do in your free time. The work you've put into this project is amazing!

If I had better knowledge of C then I'd love to contribute, but since I've only written some very basic programs in C, then I'm probably not the best candidate for this.

If there is anything I can help with though (PHP code, docs, etc) then please let me know.

**Comment by jgmdev** [comment] 2015-05-25 14:56
PHP 7 support was added to phpbrew which is an easy way to install and test different php versions. https://github.com/phpbrew/phpbrew/issues/462 phpbrew project should facilitate compiling wxphp against php 7 even if you already have a php environment setup.

**Comment by jgmdev** [comment] 2015-11-22 21:58
Closing this since it is a duplicate of issue #61 and there's a php7 branch in order to start working on this.

**Closed by jgmdev** 2015-11-22 21:58 UTC
