### ISSUE TITLE
The wxphp run ZTS mode has segment error when use wxApp initialize

### ISSUE THREAD

**Issue by chopins** [wxphp/wxphp#70] opened 2014-11-04 02:56 UTC
My PHP version is 5.6 and ZTS for loaded pthreads extension
My wxWidget version is 3.0.1.
below is gdb error message:

Program received signal SIGSEGV, Segmentation fault.
zend_call_function (fci=fci@entry=0x7fffffffa5d0, fci_cache=fci_cache@entry=0x0, tsrm_ls=tsrm_ls@entry=0x0)
    at /home/php-5.6.2/Zend/zend_execute_API.c:641

**Comment by chrisnharvey** [comment] 2015-01-12 12:43
For me, setting this to ```false``` seems to resolve the problem.

https://github.com/wxphp/wxphp/blob/master/src/app.cpp#L417

So this seems to be causing the problem:

```
function_called = call_user_function_ex(NULL, &phpObj, &function_name, &return_value, 0, NULL, 0, NULL TSRMLS_CC);
```

**Comment by jgmdev** [comment] 2015-01-12 21:10
Nice finding, so the issue is only reproduced on wxAppWrapper::OSXIsGUIApplication?

**Comment by chrisnharvey** [comment] 2015-01-12 23:08
It seems to be yeah.

**Comment by jgmdev** [comment] 2015-01-22 03:09
If latest commits fixed the issue on the affected platforms please close the issue. Otherwise let me know if something else popped up to fix it.

**Comment by chrisnharvey** [comment] 2015-01-26 19:44
This seems to have resolved the problem for me. Thanks @jgmdev.

Did this solve the issue for you @chopins?

**Comment by chopins** [comment] 2015-02-03 04:49
thanks @chrisnharvey , I currently can not be tested it

**Comment by jgmdev** [comment] 2015-02-09 13:57
I'm gonna close this, if something related pops up feel free to re-open.

**Closed by jgmdev** 2015-02-09 13:57 UTC
